/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArtistsIndexRouteImport } from './routes/artists/index'
import { Route as AlbumsIndexRouteImport } from './routes/albums/index'
import { Route as ArtistsArtistIdArtistNameRouteImport } from './routes/artists/$artistId.$artistName'
import { Route as AlbumsAlbumIdAlbumNameRouteImport } from './routes/albums/$albumId.$albumName'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistsIndexRoute = ArtistsIndexRouteImport.update({
  id: '/artists/',
  path: '/artists/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumsIndexRoute = AlbumsIndexRouteImport.update({
  id: '/albums/',
  path: '/albums/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistsArtistIdArtistNameRoute =
  ArtistsArtistIdArtistNameRouteImport.update({
    id: '/artists/$artistId/$artistName',
    path: '/artists/$artistId/$artistName',
    getParentRoute: () => rootRouteImport,
  } as any)
const AlbumsAlbumIdAlbumNameRoute = AlbumsAlbumIdAlbumNameRouteImport.update({
  id: '/albums/$albumId/$albumName',
  path: '/albums/$albumId/$albumName',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/albums/': typeof AlbumsIndexRoute
  '/artists/': typeof ArtistsIndexRoute
  '/albums/$albumId/$albumName': typeof AlbumsAlbumIdAlbumNameRoute
  '/artists/$artistId/$artistName': typeof ArtistsArtistIdArtistNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/albums': typeof AlbumsIndexRoute
  '/artists': typeof ArtistsIndexRoute
  '/albums/$albumId/$albumName': typeof AlbumsAlbumIdAlbumNameRoute
  '/artists/$artistId/$artistName': typeof ArtistsArtistIdArtistNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/albums/': typeof AlbumsIndexRoute
  '/artists/': typeof ArtistsIndexRoute
  '/albums/$albumId/$albumName': typeof AlbumsAlbumIdAlbumNameRoute
  '/artists/$artistId/$artistName': typeof ArtistsArtistIdArtistNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/albums/'
    | '/artists/'
    | '/albums/$albumId/$albumName'
    | '/artists/$artistId/$artistName'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/albums'
    | '/artists'
    | '/albums/$albumId/$albumName'
    | '/artists/$artistId/$artistName'
  id:
    | '__root__'
    | '/'
    | '/albums/'
    | '/artists/'
    | '/albums/$albumId/$albumName'
    | '/artists/$artistId/$artistName'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlbumsIndexRoute: typeof AlbumsIndexRoute
  ArtistsIndexRoute: typeof ArtistsIndexRoute
  AlbumsAlbumIdAlbumNameRoute: typeof AlbumsAlbumIdAlbumNameRoute
  ArtistsArtistIdArtistNameRoute: typeof ArtistsArtistIdArtistNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artists/': {
      id: '/artists/'
      path: '/artists'
      fullPath: '/artists/'
      preLoaderRoute: typeof ArtistsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/albums/': {
      id: '/albums/'
      path: '/albums'
      fullPath: '/albums/'
      preLoaderRoute: typeof AlbumsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artists/$artistId/$artistName': {
      id: '/artists/$artistId/$artistName'
      path: '/artists/$artistId/$artistName'
      fullPath: '/artists/$artistId/$artistName'
      preLoaderRoute: typeof ArtistsArtistIdArtistNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/albums/$albumId/$albumName': {
      id: '/albums/$albumId/$albumName'
      path: '/albums/$albumId/$albumName'
      fullPath: '/albums/$albumId/$albumName'
      preLoaderRoute: typeof AlbumsAlbumIdAlbumNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlbumsIndexRoute: AlbumsIndexRoute,
  ArtistsIndexRoute: ArtistsIndexRoute,
  AlbumsAlbumIdAlbumNameRoute: AlbumsAlbumIdAlbumNameRoute,
  ArtistsArtistIdArtistNameRoute: ArtistsArtistIdArtistNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
